import {test} from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import ts from 'typescript';
function load(file,deps={},globals={}){const exports={};vm.runInNewContext(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,{exports,require:n=>deps[n]??{},...globals});return exports;}
const solar=load('src/data/solarDemo.ts');
const env={SARVAM_API_KEY:'test',SARVAM_AGENT_ID:'property',SARVAM_DEMO_AGENT_ID:'public',SARVAM_META_AGENT_ID:'meta',SARVAM_META_APP_VERSION:'4',SARVAM_WEBHOOK_SECRET:'secret',SARVAM_PHONE_NUMBER:'+918000000000',SARVAM_ORG_ID:'org',SARVAM_WORKSPACE_ID:'ws',SARVAM_CONNECTION_ID:'conn',NEXT_PUBLIC_APP_URL:'https://demo.example.com'};
function config(e=env){return load('src/lib/sarvam/config.ts',{'@/data/solarDemo':solar},{process:{env:e},URL}).getSarvamConfig;}
test('Solar has a separate agent; existing property, public and Meta mappings remain unchanged',()=>{const get=config();assert.equal(get().appId,'property');assert.equal(get(true).appId,'public');assert.equal(get(false,true).appId,'meta');assert.equal(get(false,true).appVersion,4);assert.equal(get(false,false,true).appId,solar.SOLAR_AGENT_ID);assert.equal(get(false,false,true).versionFilter,'latest_committed');assert.equal(get(false,false,true).connectionId,'conn');assert.equal(config({...env,SARVAM_API_KEY:''})(false,false,true),null);});
test('Solar version override does not affect other agents',()=>{const get=config({...env,SARVAM_SOLAR_APP_VERSION:'1'});assert.equal(get(false,false,true).appVersion,1);assert.equal(get(true).appVersion,null);assert.equal(get(false,true).appVersion,4);});
test('Solar sends only Solar variables, clearing the template name and preserving webhook correlation',async()=>{let body;const Provider=load('src/lib/sarvam/sarvam-provider.ts',{'@/data/solarDemo':solar,'./config':{getSarvamConfig:config()},'./agent-prompt':{buildAgentInstructions:()=>{throw Error('Property prompt must not run for Solar');}},'@/data/publicDemo':{PUBLIC_DEMO_ID:'bettercallz-live'},'@/lib/meta-leads/constants':{META_PROJECT_ID:'bettercallz-meta'}},{process:{env:{NODE_ENV:'production'}},fetch:async(url,opts)=>{body=JSON.parse(opts.body);return {ok:true,json:async()=>({attempt_id:'test-attempt'})}}}).SarvamVoiceProvider;const result=await new Provider().createCall({projectContext:{projectId:'solar'},phoneNumber:'+919971365666',callId:'solar-call'});assert.equal(body.app_config.app_id,solar.SOLAR_AGENT_ID);assert.deepEqual(body.app_config.agent_variables,{user_name:''});assert.equal(body.webhook_config.metadata.callId,'solar-call');assert.equal(result.providerCallId,'test-attempt');});
test('Solar fails closed before creating records when live configuration is unavailable',async()=>{let writes=0;const svc=load('src/lib/calls/service.ts',{'@/data/solarDemo':solar,'@/lib/knowledge/service':{getProject:()=>solar.solarProject},'@/data/publicDemo':{PUBLIC_DEMO_ID:'bettercallz-live'},'@/lib/sarvam/config':{getSarvamConfig:()=>null},'@/lib/supabase/env':{isSupabaseConfigured:()=>true},'@/lib/db/repository':{createLead:()=>{writes++}}});await assert.rejects(()=>svc.startCall({projectId:'solar',phone:'9971365666'}),/temporarily unavailable/);assert.equal(writes,0);});
test('Solar listing does not replace F Premiere',()=>{const demo=load('src/data/demoProject.ts');const knowledge=load('src/lib/knowledge/service.ts',{'@/data/solarDemo':solar,'@/data/demoProject':demo,'@/data/publicDemo':{PUBLIC_DEMO_ID:'bettercallz-live'}});assert.deepEqual(Array.from(knowledge.listProjects(),p=>p.id),['f-premiere','solar']);assert.equal(knowledge.getProject('f-premiere').name,'F Premiere');assert.equal(knowledge.getProject('solar').name,'Solar Lead Qualification');});
